# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'SRGiftPick' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    
    # Pods for SRGiftPick
    pod 'AFNetworking'
    pod 'SDWebImage'
    pod 'MJRefresh'
    pod 'Masonry'
    pod 'SVProgressHUD'
    pod 'MJExtension'
    pod 'NJKWebViewProgress'
    pod 'DACircularProgress'
    pod 'pop'
    
end
