# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'SRBSBuDeJie' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    
    # Pods for SRBSBuDeJie
    pod 'MJExtension', '~> 2.5.2'
    pod 'MJRefresh', '~> 2.3.2'
    pod 'Masonry', '~> 0.6.2'
    pod "AFNetworking"
    pod "SDWebImage"
    pod "SVProgressHUD"
    pod "DACircularProgress"
    pod "pop"
    
end
